In [16]:
import numpy as np

In [1]:
print('hello world')

hello world


In [17]:
## creation of array 1D 
arr = np.array([25,41,63,66,85,74])
arr 

array([25, 41, 63, 66, 85, 74])

In [18]:
type(arr)
# ndarray  ==> n diminensional array 

numpy.ndarray

In [19]:
arr.size  # no. of  item 

6

In [20]:
len(arr)

6

In [21]:
arr.ndim   # to check the dimension of array 

1

In [22]:
arr = np.array([25,41,63,66,85,74,25.01,'upflairs',True])
arr 
## similar type store  
## array similar item 

array(['25', '41', '63', '66', '85', '74', '25.01', 'upflairs', 'True'],
      dtype='<U32')

In [23]:
arr.dtype

dtype('<U32')

In [24]:

print(np.__version__)

2.1.0


In [25]:
ls = [25,41,63,66,85,74]
arr = np.array(ls)
arr 

array([25, 41, 63, 66, 85, 74])

In [26]:
arr[-1]

np.int64(74)

In [27]:
arr[::] # start = 0  , stoping  = end , jump == 1 

array([25, 41, 63, 66, 85, 74])

In [28]:
arr[-1] = 500

In [29]:

arr

array([ 25,  41,  63,  66,  85, 500])

In [30]:
arr + 2

array([ 27,  43,  65,  68,  87, 502])


2D arrays

In [31]:
ls = [[1,2,3],
     [4,5,6],
     [7,8,9]]

ls 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [32]:
type(ls)

list

In [33]:

ls[-1]

[7, 8, 9]

In [34]:
arr2 = np.array(ls)
arr2 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:

# 9  = 90  
arr2[-1,-1] = 90 

In [36]:

arr2 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

In [37]:
arr = np.random.randint(1,200,500)
arr # single dimension array 
# 1 bag of marbles 10 pick

array([116, 192,  57,  22,   8, 192,  27,  27, 112, 131,  94, 134, 153,
        96,  93, 129,  63, 160,  50, 111, 199, 112, 192, 180, 187, 166,
       110, 169,  81, 169, 112, 140,  27,  14,  89,  28, 130,  53,  70,
       123, 116,  46,  94,  93, 147, 142,  64, 181, 146,  33, 136, 137,
       145, 121,  77,  62,  68,  84, 171, 141, 183,  47,  98,  90, 109,
       184,  31,  50, 129,  95, 101, 192, 193, 118,  59, 111, 101, 138,
       167, 113, 183,  92,  73, 177, 178,  92,  85,  60, 117,  15,  76,
        62,  12, 158,  24,   9, 139, 159,  71,  86, 139, 177, 162,  44,
        88,  86, 145,  53,  39,  25, 133, 186,  73,   6,  77, 160, 103,
        65, 158,  49,  96,  46, 184,  19,  45, 196,  64, 177,  31,  25,
        18, 185,  41, 133,  80, 112,  48, 173,  66,  90, 194,  17,   1,
        52,  34,  81,  70, 197,  27, 117, 112, 140,  32,  37,  11,  97,
        48, 106, 177,  47, 101,  83, 193, 166, 104, 169, 196, 123, 177,
        12, 179, 157,  12, 132, 111,  34,  10,  71, 141, 184,  1

In [38]:
# arr  filter all thos item that are less than equal to 100  
# comments ---> how many item in your arrays 

arr[arr <= 100]

array([ 57,  22,   8,  27,  27,  94,  96,  93,  63,  50,  81,  27,  14,
        89,  28,  53,  70,  46,  94,  93,  64,  33,  77,  62,  68,  84,
        47,  98,  90,  31,  50,  95,  59,  92,  73,  92,  85,  60,  15,
        76,  62,  12,  24,   9,  71,  86,  44,  88,  86,  53,  39,  25,
        73,   6,  77,  65,  49,  96,  46,  19,  45,  64,  31,  25,  18,
        41,  80,  48,  66,  90,  17,   1,  52,  34,  81,  70,  27,  32,
        37,  11,  97,  48,  47,  83,  12,  12,  34,  10,  71,  14,  24,
        60,  34,  63,  91,  84,  95,  10,  11,  96,  70,   2,  88,  54,
        47,  61,  82,  42,  22,  37,  90,  18,  74,  64,  19,  11,  50,
        93,  69,  13,  13,  24,  37,   2,  32,  43,  66,  69,  43,  12,
        10,  92,  42,  81,  34,  47,   7,   3,  92,   7,  37,  71,  20,
        27,  93,  53,  18,  19,  76,  15,  50,   4,  92,  48,  42,  42,
        93,  34,  23,  34,  98,  97,  98,  37,  97,  53,  61,  93,  13,
        84,  88,   9,  80,  51,  63,  94,  28,  31,  58,  28,  5

In [39]:
arr[arr <= 100].size

253

In [40]:
len(arr[arr <= 100])

253

In [41]:
arr[arr <= 100].shape 

(253,)

In [42]:

arr2 = np.random.randint(1,200,(10,5))
arr2

array([[132, 129, 116,  24, 137],
       [122,  96,  54, 122, 142],
       [ 53,   6, 157,  76, 100],
       [128,  30,  15, 122, 174],
       [135, 177, 121, 174,  65],
       [ 55, 172,  96,  14, 107],
       [103, 195,  59, 156, 110],
       [172, 132,  31, 162, 183],
       [133,  48, 173,  69, 179],
       [114, 100, 184, 179,   6]], dtype=int32)

In [43]:

arr2 = np.random.randint(1,200,(10,6))
arr2

array([[ 83,  78,  11,  77,  91,   3],
       [ 59, 127, 168,  19, 156, 121],
       [174,  65,  88,  78, 186,  81],
       [106,  69,  61,  43,  25, 100],
       [ 70, 190, 176,  80, 140, 152],
       [ 11,  31,  10, 160, 119,  78],
       [  2,  83,  55,  11, 191, 185],
       [116,  39, 142,  22, 104, 118],
       [  3,  40, 186, 120, 118, 165],
       [100, 104, 111, 180, 194,  37]], dtype=int32)

In [44]:
arr = np.zeros(10)
arr # 1D array 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
arr.dtype

dtype('float64')

In [46]:
arr = np.zeros((10,5))  # 2D array 
arr 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
arr = np.ones(10)
arr 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
arr = np.ones((10,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
ls = [0,1,2,3,4,5,6,7,8,9]
ls 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:

ls = list(range(10))
ls 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr = np.arange(60)
arr  # single 1D 


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [53]:
# 2D , 60
# 10,6
arr.reshape(6,10)  # 10 *  6 == 60 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [54]:
arr.reshape(3,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])

In [55]:
arr = arr.reshape(6,10)  # 10 *  6 == 60 

In [56]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:

# message = s.recvfrom(100)
# sender_address = message[1]
# reply_message = "Thank you for sending message "
# encryptmessage  = ......... 
# s.sendto(encryptmessage,sender_address)

In [57]:

### creation of 3D array
arr1D = [1,2,3]
arr2D = [[1,2,3],[1,2,3],[1,2,3]]  # [1D,1D,1D]
arr3D = [[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]     # [2D,2D,2D,2D]

In [58]:
arr = np.array(arr3D)
arr 

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [59]:
arr.ndim

3

In [60]:
arr3 = np.random.randint(1,200,(3,5,3))
arr3 
# (10,5)  (row,column)

array([[[  4,  17, 168],
        [197,  79, 121],
        [158,  80, 113],
        [  7,  63,  51],
        [112, 134, 176]],

       [[ 94,  54,  92],
        [163,  61,  50],
        [ 27,  56, 136],
        [145, 145,  38],
        [128, 123,  14]],

       [[ 33,   8,  43],
        [100, 170,  81],
        [ 36,  91,  76],
        [146,  80, 138],
        [ 49, 136, 137]]], dtype=int32)

In [61]:

arr3.shape 
#(table,  row , column)

(3, 5, 3)

In [62]:

arr3.ndim 

3

In [63]:

arr3.ndim 

3

In [64]:

arr = np.array([9,7,8])
arr 

array([9, 7, 8])

In [ ]:
# max(arr)   # min(arr)

In [65]:
np.mean(arr)   # average 

np.float64(8.0)

In [66]:

np.sum(arr)

np.int64(24)

In [67]:
np.argmin(arr)
# argmin returns index of minimum item 

np.int64(1)

In [68]:
np.argmax(arr)

np.int64(0)

In [69]:
arr.sort()  # ascending order 

In [70]:
arr  # ascending order 

array([7, 8, 9])

In [71]:
arr[::-1]   # descending order 

array([9, 8, 7])